import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/custom.scss";
import 'jquery';
import 'popper.js';
import 'bootstrap-icons/font/bootstrap-icons.css';

import BootstrapJsBundle from "@/components/BootstrapJsBundle";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Web Sorteos",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={`${inter.className}`}>
        <BootstrapJsBundle />
        <Navbar />
        {children}
        <Footer />
        </body>
        </html>
    );
}
