import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/custom.scss";
import BootstrapJS from "@/components/BootstrapJS";
import Navbar from "@/components/Navbar";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Web Sorteos",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={`${inter.className}`}>
        <BootstrapJS />
        <Navbar />
        {children}
        </body>
        </html>
    );
}
